#!/usr/bin/env python3

head='''title: Römertopf-Brot
duration: 3:30 h
servings: 1
story: Dieses Brot verlangt abgesehen von ein wenig Geduld nur wenige sehr leichte Arbeitsschritte und schmeckt trotzdem ordentlich.
ingredients:
      - [500, g, 'Mehl, verschiedene nach Belieben']
      - [400, ml, Lauwarmes Wasser]
      - [1, TL, Zucker]
      - [21, g, Frische Hefe]
      - [2, TL, Salz]
      - [75, g, Sonnenblumenkerne und/oder Kürbiskerne]
      - [50, g, Leinsamen]
tools:
     - Römertopf
oven_instructions: 220°C Ober-/Unterhitze, 30 Minuten → 200°C Ober-/Unterhitze, 15 – 20 Minuten 
'''

instructions = '''
* Hefe und Zucker im lauwarmen Wasser auflösen.
* Salz, Samen und Mehl vermengen.
* Wassergemisch langsam im Mehl einrühren.
* Teig mit dem Knethaken kneten, bis er leicht glänzt.
* Den Deckel des Römertopf mit Wasser befüllen und stehen lassen.
* Den  Deckel insgesamt 2:40 Stunden stehen lassen. Den Teig 3 Stunden ruhen lassen.
* nach 2:40 h den Römertopf-Boden mit Backpapier auskleiden, das Wasser im Deckel wegschütten und zusammen im unteren Drittel bei 220°C Ober-/Unterhitze vorheizen.
* Wenn der Ofen vorgeheizt ist, den Römertopf heraus nehmen und den Teig einfüllen. Mit etwas Wasser bestreuen, zudecken und in den Ofen stellen.
* Nach 30 Minuten das Brot aus dem Topf nehmen und weitere 15 – 20 Minuten backen.
* Quelle: https://www.youtube.com/watch?v=Yu4zqIjClqo
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, image_url_path='/bakery/images/roemertopf-brot.jpg', additional_image_url_paths=None)
