#!/home/pi/python/bin/python
head='''
title: Alpenroggen-Mischbrot
duration: ca. 13 h Sauerteig, 50 Minuten Stückgare, insgesamt ca. 15 h.
story: 'Würzig aromatisches Alpenroggenmehl trifft auf kleberstarkes Ciabattamehl. Ergibt ein würziges Brot mit elastischer und saftiger Krume. TA 182. Ergibt ca. 400g Brot.'
ingredients:
     Sauerteig:
          - [12.5, g, Anstellgut]
          - [125, g, Roggenvollkornmehl]
          - [125, g, Wasser (45°C)]
     Hauptteig:
          - [Sauerteig]
          - [120, g, Alpenroggenmehl (oder Roggenmehl Type 1370)]
          - [105, g, 'Ciabattamehl Tipe 0 mit 14% Eiweiß (oder Weizenmehl Type 550)']
          - [7, g, Salz]
          - [1.5, g, Trockenhefe]
          - [7, g, Honig]
          - [162, g, 'Wasser (40°C) (bei Verwendung von Ersatzmehlen: 138 g)']
tools:
     - Gärkorb
     - Gusseisenpfanne
     - Sprühflasche
oven_instructions: 240°C Ober-/Unterhitze fallend auf 210°C, 40 – 50 Minuten
'''

instructions='''
 Möglicher Zeitplan: Morgens um 9 Uhr den Sauerteig mischen, um 22 Uhr mit dem Hauptteig fortfahren und am selben Abend backen.

## Sauerteig ansetzen

* Das Anstellgut mit dem Wasser vermischen. Anschließend das Mehl hinzugeben und alles zu einer homogenen Masse vermischen.
* 12 – 14 h bei ca. 24°C reifen lassen.

## Hauptteig

* Trockenhefe und Honig im Wasser auflösen.
* Den gereiften Sauerteig hinzugeben und im Wasser verteilen.
* Restliche Zutaten dazugeben und alles manuell zu einer homogenen Masse verkneten.
* Den Teig mit dem Knethaken 9 Minuten langsam kneten.
* 30 Minuten ruhen lassen.
* Arbeitsfläche bemehlen, Gärkorb bemehlen und daneben stellen.
* Den Teig auf die Arbeitsfläche kippen und rundwirken: D.h. die Ränder zur Mitte hin falten und dann den Teigling auf die bemehlte Arbeitsfläche umdrehen und noch etwas rund schieben.
* Mit dem Schluss nach unten ins Gärkörbchen setzen und 50 Minuten ruhen lassen.
* Nach 35 Minuten schonmal den Ofen mit Gusseisenpfanne auf 240°C Ober-/Unterhitze vorheizen.
* Den Teig auf ein mit Backpapier ausgekleidetes Schneidebrett stürzen und 1 Minute warten.
* Dann auf die Gusseisenpfanne heben und in den Ofen schieben.
* Nach 2 Minuten kräftig Wasser in den Ofen sprühen und die Temperatur auf 210°C herunterregeln.
* Ca. 40 – 50 Minuten weiter backen, bis eine braune und stellenweise dunkelbraune Kruste entstanden ist.
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, '/bakery/images/alpenroggen-mischbrot.jpg')
