#!/home/pi/python/bin/python
head='''
title: Landbrot mit Sauerteig
duration: ca. 8 h Sauerteig, 20 min Autolyse, 2.5 h Stockgare, 12 h Stückgare, 45 min backen, insgesamt ca. 24 h.
ingredients:
    Sauerteig:
        - [67, g, Weizensauerteig]
        - [67, g, Wasser]
        - [67, g, Weizenmehl Type 550]
    Hauptteig:
        - [112.5, g, Weizensauerteig]
        - [280, g, Wasser]
        - [262.5, g, Weizenmehl Type 550 (14% Gluten)]
        - [67.5, g, Alpenroggenmehl]
        - [67.5, g, Vollkornweizenmehl]
        - [9, g, Salz]
        - [1.9, g, Backmalz]
        - [0.75, g, Trockenhefe]
        - [20, g, Saaten (optional)]
    Für die Kruste:
        - [Saaten (optional)]
tools:
     - Teigschaber
     - Gusseisentopf
oven_instructions: 260°C Ober-/Unterhitze vorzeigen, 245°C mit Deckel 10 Minuten, 230°C ohne Deckel 30 - 35 Minuten
'''
instructions = '''

* Den Sauerteig verdoppeln lassen und 87.5 g als Anstellgut zurück in den Kühlschrank stellen.
* Alle Zutaten außer Salz auf niedriger Stufe mischen und anschließend bei Zimmertemperatur 20 Minuten ruhen lassen (Autolyse).
* Salz (und optional Saaten) hinzufügen und auf mittlerer Stufe kneten bis der Teig anfängt zu glänzen.
* Abgedeckt bei Zimmertemperatur 2.5 h gehen lassen. Dabei nach 60 und nach 120 Minuten je einmal dehnen und falten (Stockgare).
* Falls keine Saaten auf die Kruste sollen, Gärkörbchen bemehlen.
* Teig rundwirken und für 20 Minuten abgedeckt ruhen lassen (Vorformen)
* Teigling langwirken und optional in Saaten rollen.
* Mit Schluss nach oben in Gärkörbchen legen.
* Abgedeckt im Kühlschrank für 12 h reifen lassen (Stückgare).
* Backofen mit Gusseisentopf auf 250°C Ober-/Unterhitze vorheizen.
* Teigling auf ein Brett mit Backpapier stürzen und länglich einscheniden.
* Mit Backpapier auf den heißen Gusseisentopf transferieren, mit etwas Wasser besprühen und mit Deckel in den Ofen schieben.
* Ofen auf 245°C reduzieren.
* Nach 10 Minuten Deckel entfernen und Temperatur auf 230°C absenken.
* Weitere 30 - 35 Minuten backen.
* Quelle: https://www.el-gusto.net/rezept/landbrot-mit-sauerteig/
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, '/bakery/images/landbrot-mit-sauerteig.jpg')
