#!/usr/bin/env python3

head='''title: Blaubeer-Muffins
story: Sehr einfach zu backen. Der Muffin ist oben knusprig und innen drin luftig, weich und saftig. Die Kruste ist etwas süßer als der Rest. Ergibt 12 Muffins.
ingredients:
     Rührteig:
          - [125, g, Butter]
          - [60, g, Zucker]
          - [2, Eier]
          - [1, Pk, Vanillezucker]
          - [1, TL, Zitronenschale]
          - [250, g, Mehl]
          - [2, TL, Backpulver]
          - [150, ml, Buttermilch]
          - [250, g, Blaubeeren]
     Streusel:
          - [130, g, Mehl]
          - [60, g, Zucker]
          - [1, Pk, Vanillezucker]
          - [110, g, Butter]
tools:
     - Muffinblech
     - Papierförmchen
     - Eisportionierer
oven_instructions: 160°C Umluft, 30 Minuten
'''

instructions = '''
* Muffinblech mit Papierförmchen auslegen
* Butter, Zucker und Vanillezucker verrühren
* Hintereinander die Eier unterrühren
* Zitronenschale, Mehl und Backpulver vermischen
* Buttermilch und Mehlgemisch abwechselnd in das Buttergemisch einrühren
* Teig mit Eisportionierer in die Muffinförmchen geben
* In jeden Muffin 7 Blaubeeren drücken
* Ofen auf 160°C Umluft vorheizen
* Streuselzutaten verkneten
* Stücke abreißen und auf den Muffins verteilen
* Die Muffins 25 Minuten auf mittlerer Schiene backen
* Nach dem Backen 10 Minuten abkühlen lassen.
* Muffins mit einer leichten Drehbewegung aus dem Muffinblech herauslösen.
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, image_url_path='/bakery/images/blaubeer-muffins.jpg', additional_image_url_paths=None)
