#!/usr/bin/env python3

head='''title: Hildes Zwetschgenkuchen mit Zimtstreuseln
duration: 1:20 h (40 Minuten Arbeit)
servings: 1 Kuchen (Springform ⌀ 26 cm)
story: Ein beliebter Zwetschgenkuchen auf chefkoch.de
ingredients:
    Kuchenboden:
        - [150, g, Mehl Type 405]
        - [1, Pk, Sahnepuddingpulver]
        - [120, g, Butter]
        - [60, g, Zucker]
        - [1, Ei]
        - [1, Msp, Backpulver]
        - [1, Schuss, Rum]
        - [500, g, Zwetschgen]
    Streusel:

        - [100, g, Mehl]
        - [75, g, Butter]
        - [50, g, Zucker]
        - [2, Pk, Vanillinzucker]
        - [1, TL, Zimt]
tools:
     - Springform ⌀ 26 cm
'''

instructions = '''
* Springform mit Backpapier auskleiden und Rand einfetten.
* Alle Zutaten vom Mehl bis zum Rum verkneten, auf dem Springformboden verteilen und einen Rand hochziehen.
* Zwetschgen entkernen, vierteln und von außen nach innen den Kuchen belegen. Für zu große Hohlräume Zwetschgen zurecht schneiden und befüllen.
* Streuselzutaten verkneten und als grobe Stückchen auf den Zwetschgen verteilen.
* Bei 180° C Ober-/Unterhitze ca 35 - 40 Minuten backen.
* Quelle: https://www.chefkoch.de/rezepte/584841157633103/Hildes-Zwetschgenkuchen-mit-Zimtstreuseln.html
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, image_url_path='/bakery/images/hildes-zwetschgenkuchen-mit-zimtstreuseln.jpg', additional_image_url_paths=None)
