#!/usr/bin/env python3

head='''title: Saftiger Nusskuchen mit Zimtglasur
duration: 30 Minuten Arbeitszeit, ca. 1 Stunde Backzeit
servings: Torte 24 cm Springform
story: Sehr saftiger und aromatischer Haselnusskuchen
ingredients:
     Kuchen:
          - [400, g, Haselnüsse (gemahlen)]
          - [1, Pk, Backpulver]
          - [4, EL, Mehl (gehäufte Esslöffel)]
          - [1, TL, Zimt]
          - [250, g, brauner Zucker]
          - [1, Prise, Salz]
          - [2, TL, Vanille-Paste]
          - [200, g, weiche Butter]
          - [4, Eier L]
     Glasur:
          - [3, EL, Milch]
          - [150, g, Puderzucker]
          - [1, TL, Zimt]

oven_instructions: 170°C Ober-/Unterhitze, dann 60 – 70 Minuten
additional_images:
     'An image of Anschneide-Trick': /bakery/images/saftiger-nusskuchen-mit-zimtglasur-baklava-schneiden.png
'''

instructions = '''
* Gemahlene Haselnüsse, Backpulver, Mehl und Zimt in einer Schüssel mischen.
* Eier trennen. In einer Schüssel das Eiweiß mit dem Salz steif schlagen.
* In zweiter Schüssel Eigelbe und Zucker schaumig schlagen.
* Butter und Vanille-Paste dazu geben und weiter rühren.
* Mehlgemisch unter rühren hineingeben.
* 3 – 4 EL Eischnee unterrühren. Den Rest vorsichtig unterheben.
* Springform fetten und Rührteig hinein füllen.
* Bei 170°C Ober-/Unterhitze für 60 – 70 Minuten backen. Stäbchenprobe verrät, ob der Kuchen fertig ist.
* Fertigen Kuchen in der Form 15 Minuten abkühlen lassen.
* Springformrand lösen und Kuchen vollständig abkühlen lassen.
* Die Glasur-Zutaten zusammenrühren und Kuchen nach Belieben überziehen.
* Kuchen anschneiden: Wenn man z.B. für eine Veranstaltungen viele kleine Stücke schneiden möchte, kann man eine schöne Technik anwenden, die anscheinend ab und zu beim Schneiden von Baklava zur Anwendung kommt. Siehe Anleitung im Bild. Je nachdem, wie groß die Stücke sein sollen, kann man in Schritt 2 und 3 weniger oder mehr parallele Linien schneiden.

* Quellen: https://zimtkeksundapfeltarte.com/2021/11/14/bester-saftiger-nusskuchen-mit-zimtglasur/, https://shop.kochdichturkisch.de/2014/04/30-baklava-schneiden-so-gehts/
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, image_url_path='/bakery/images/saftiger-nusskuchen-mit-zimtglasur.jpg', additional_image_url_paths={'An image of Anschneide-Trick': '/bakery/images/saftiger-nusskuchen-mit-zimtglasur-baklava-schneiden.png'})
