#!/usr/bin/env python3

head='''title: Vanillekipferl
story: Einfaches Vanillekipferl-Rezept, ergibt 2 Bleche.
ingredients:
    Teig:
          - [80, g, Zucker]
          - [2, Pk, Vanillezucker]
          - [210, g, Butter]
          - [250, g, Mehl Type 405]
          - [100, g, gemahlene Mandeln]
    Ummantelung:
          - [Vanillezucker]
oven_instructions: 175°C Umluft, 13 Minuten
'''

instructions = '''
* Teigzutaten miteinander verkneten.
* Teig zur Kugel formen und in Folie 2 Stunden im Kühlschrank ruhen lassen.
* Teig aus dem Kühlschrank nehmen und auf Raumtemperatur aufwärmen lassen.
* Teigstücke abreißen und zu Kipferl bevorzugter Größe Formen. Dafür zwischen den Händen länglich rollen und anschließend leicht krümmen. Die Kipferl sollten zu den Enden hin schmaler werden.
* Im vorgeheizten Ofen bei 175°C ca. 13 Minuten backen bis sie leicht bräunlich werden.
* Etwa 3 Minuten abkühlen lassen, anschließend in Vanillezucker wenden.
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, image_url_path='/bakery/images/vanillekipferl.jpg', additional_image_url_paths=None)
