#!/usr/bin/env python3

head='''title: Bánh Củ Cải (Vietnamesischer Rettichkuchen)
duration: 1:00 h
story: Warmes Frühstück
ingredients:
    - [400, g, Rettich (Abtropfgewicht)]
    - [200, g, Reismehl]
    - [1.5, EL, Kartoffelstärke/Tapiokastärke]
    - [450, ml, warmes Wasser]
    - [3, Morcheln]
    - [Salz]
    - [Zucker]
    - [Speisestärke]
tools:
     - Form
     - Dampfgarer
'''

instructions = '''
* Morcheln einweichen
* Rettich schälen und in Streifen hobeln
* 5 Minuten in Salz stehen lassen. Dann auswaschen und mit mäßiger Kraft ausdrücken. Jetzt Abtropfgewicht messen!
* Rettich kurz anbraten
* Morcheln sehr klein hacken und alle Zutaten miteinander vermengen.
* Im Dampfgarer abgedeckt ca. 30 Minuten garen. Der Kuchen ist fertig, wenn die obere Seite etwas glasig wirkt.
* Bei Raumtemperatur vollständig abkühlen lassen. Anschließend über Nacht im Kühlschrank stehen lassen.
* Zur Zubereitung in der Pfanne mit Ei anbraten.
* Am Tisch zum Beispiel mit Maggi und Sốt Sa tế (vietnamesischer Saté-Soße) würzen.
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, image_url_path='/bakery/images/banh-cu-cai.jpg', additional_image_url_paths=None)
