#!/usr/bin/env python3

head='''title: 蔥油餅 (Cōng Yóu Bǐng/Lauchzwiebel-Öl-Pfannkuchen)
duration: 1:00 h
story: Ein taiwanesisches Street-Food für Fans von knusprigem Teig. Ergibt 2 Stück.
ingredients:
    - [400, g, Mehl Type 405 12% Protein]
    - [280, g, Kaltes Wasser]
    - [2, TL, Salz]
    - [Öl]
    - [2, Stangen, Lauchzwiebeln]
tools:
     - Nudelholz
'''

instructions = '''
* Wasser, Mehl und Salz verkneten.
* Teig in zwei gleiche Hälften teilen und jeweils zu runden Kugeln formen.
* 20 Minuten unter einem feuchten Tuch ruhen lassen.
* Währenddessen Lauchzwiebeln in schmale Ringe schneiden.
* Teig auf einer bemehlten Fläche zu einer Dicke von 2 mm ausrollen.
* Um Ankleben zu verhindern, regelmäßig unter dem Teig nachmehlen.
* Öl im Zentrum verteilen und die Seiten einschlagen, um das Öl zu verteilen.
* Lauchzwiebeln gleichmäßig verteilen.
* Den Teig eng aufrollen und die Enden verschließen.
* Die Teigrolle spiralförmig gegeneinander verdrehen, um sie straffer zu machen.
* Die aufgedrehte Rolle ähnlich wie eine Schnecke zu einem Turm aufschichten.
* Arbeitsfläche ölen und Teigtürme darauf platzieren und unter einem feuchten Tuch 20 Minuten ruhen lassen.
* Die Teigtürme zu 1 cm dicken Scheiben platt drücken.
* Eine Pfanne ohne Öl heiß werden lassen und bei mittlerer Hitze einen Teigling hinein geben.
* Den Teigling auf der einen Seite ohne Deckel leicht goldbraun anbraten, dann wenden und mit Deckel auch die andere Seite leicht goldbraun backen.
* Teigling jeweils auf beiden Seiten einmal anheben und mit Kraft in die Pfanne schlagen.
* Öl hinzugeben und Teigling in Kreisbewegungen darin auf beiden Seiten fertig braten.
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, image_url_path='/bakery/images/cong-you-bing.jpg', additional_image_url_paths=None)
