#!/home/pi/python/bin/python
head='''
title: Thịt Chưng Trứng Muối (Vietnamesische Fleischpastete mit salzigen Eiern)
duration: 2:00 h (20 – 30 Minuten Arbeit)
servings: 7 Portionen
story: 'Diese Fleischpastete ist häufiger Bestandteil meines Lieblingsgerichts aus Vietnam: Cơm Tấm.'
ingredients:
    - [250, g, Schweinehackfleisch]
    - [3, Salzlaken-Eier]
    - [1, Ei]
    - [1, Eigelb]
    - [3 Morcheln]
    - [1, kl. Packung, Glasnudeln]
    - [2, Lauchzwiebeln]
    - [Pfeffer]
    - [2, TL, Fischsoße]
    - [Zucker]
    - [Chili]
tools:
     - Form
     - Dampfgarer
'''

instructions='''
* Morcheln einweichen (20 Minuten), Glasnudeln einweichen (3 Minuten).
* Morcheln und Glasnudeln in dünne Streifen schneiden.
* Lauchzwiebeln in Ringe schneiden. Eine kleine Handvoll zum Garnieren beiseite legen.
* Hackfleisch, Morcheln, Glasnudeln, Lauchzwiebeln in einen Behälter geben.
* Das Eiweiß der Salzlaken-Eier dazu geben. Das Salzlaken-Eigelb in kleine Würfel schneiden und dazugeben.
* Das normale Ei dazugeben.
* Fischsoße, Pfeffer und Zucker dazu geben.
* Alles mit einem Löffel durchmischen.
* Die Masse muss sich sehr nass und weich anfühlen, aber sie soll nicht in Feuchtigkeit schwimmen. Entsprechend Eier dazugeben, falls es noch zu trocken wirkt.
* Eine im Kühlschrank Stunde stehen lassen.
* Abgedeckt 20 Minuten garen.
* Gegen Ende der Garzeit Chili in Ringe schneiden und das Eigelb des übrigen Eis trennen.
* Mit einem Stäbchen in die Pastete einstechen. Falls Flüssigkeit austritt, weiter garen bis der Stichtest trocken bleibt.
* Falls sich Flüssigkeit auf der Oberfläche abgesetzt hat, diese mit einem Küchentuch abtupfen.
* das verbliebene Eigelb auf der Oberfläche verstreichen und Lauchzwiebeln und Chili darauf sreuen.
* Nur 1 – 2 Minuten weiter garen, sodass das Eigelb nicht mehr flüssig ist.
* Kann sofort angeschnitten und gegessen werden.
* Zum Anrichten zB.:
* Fischsoße vorbereiten: 1:1:1 Fischsoße:Wasser:Zucker, Zitronensaft nach Geschmack, Chili
* Lauchzwiebel-Ringe kurz in Öl anbraten, nicht braun werden lassen.
* Fischsoße über den Reis gießen, mit den Lauchwziebeln in Öl garnieren, frische Gurke und Đồ Chua (sauer eingelegter Rettich und Karotte) dazu servieren.
'''

from recipe_site_generator.gemtext_recipe import print_recipe
print_recipe(head, instructions, '/bakery/images/thit-chung-trung-muoi.jpg')